// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace allurecsharpcommons {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("test-suite-result", Namespace="urn:model.allure.qatools.yandex.ru")]
    [System.Xml.Serialization.XmlRootAttribute("test-suite", Namespace="urn:model.allure.qatools.yandex.ru", IsNullable=false)]
    public partial class testsuiteresult {
        
        private long startField;
        
        private long stopField;
        
        private string nameField;
        
        private string titleField;
        
        private description descriptionField;
        
        private testcaseresult[] testcasesField;
        
        private label[] labelsField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public long stop {
            get {
                return this.stopField;
            }
            set {
                this.stopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public description description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(ElementName="test-cases", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="test-case", IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public testcaseresult[] testcases {
            get {
                return this.testcasesField;
            }
            set {
                this.testcasesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public label[] labels {
            get {
                return this.labelsField1;
            }
            set {
                this.labelsField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:model.allure.qatools.yandex.ru")]
    public partial class description {
        
        private descriptiontype typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue(descriptiontype.text)]
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public descriptiontype type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("description-type", Namespace="urn:model.allure.qatools.yandex.ru")]
    public enum descriptiontype {
        
        /// <remarks/>
        markdown,
        
        /// <remarks/>
        text,
        
        /// <remarks/>
        html,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("test-case-result", Namespace="urn:model.allure.qatools.yandex.ru")]
    public partial class testcaseresult {
        
        private long startField1;
        
        private long stopField1;
        
        private status statusField;
        
        private severitylevel severityField;
        
        private string nameField1;
        
        private string titleField1;
        
        private description descriptionField1;
        
        private failure failureField;
        
        private step[] stepsField;
        
        private attachment[] attachmentsField1;
        
        private label[] labelsField;
        
        private parameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public long start {
            get {
                return this.startField1;
            }
            set {
                this.startField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public long stop {
            get {
                return this.stopField1;
            }
            set {
                this.stopField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public status status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public severitylevel severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField1;
            }
            set {
                this.nameField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title {
            get {
                return this.titleField1;
            }
            set {
                this.titleField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public description description {
            get {
                return this.descriptionField1;
            }
            set {
                this.descriptionField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public failure failure {
            get {
                return this.failureField;
            }
            set {
                this.failureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public step[] steps {
            get {
                return this.stepsField;
            }
            set {
                this.stepsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public attachment[] attachments {
            get {
                return this.attachmentsField1;
            }
            set {
                this.attachmentsField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public label[] labels {
            get {
                return this.labelsField;
            }
            set {
                this.labelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public parameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:model.allure.qatools.yandex.ru")]
    public enum status {
        
        /// <remarks/>
        failed,
        
        /// <remarks/>
        broken,
        
        /// <remarks/>
        passed,
        
        /// <remarks/>
        skipped,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("severity-level", Namespace="urn:model.allure.qatools.yandex.ru")]
    public enum severitylevel {
        
        /// <remarks/>
        blocker,
        
        /// <remarks/>
        critical,
        
        /// <remarks/>
        normal,
        
        /// <remarks/>
        minor,
        
        /// <remarks/>
        trivial,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:model.allure.qatools.yandex.ru")]
    public partial class failure {
        
        private string messageField;
        
        private string stacktraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stack-trace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stacktrace {
            get {
                return this.stacktraceField;
            }
            set {
                this.stacktraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:model.allure.qatools.yandex.ru")]
    public partial class step {
        
        private long startField2;
        
        private long stopField2;
        
        private status statusField1;
        
        private string nameField2;
        
        private string titleField2;
        
        private attachment[] attachmentsField;
        
        private step[] stepsField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public long start {
            get {
                return this.startField2;
            }
            set {
                this.startField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public long stop {
            get {
                return this.stopField2;
            }
            set {
                this.stopField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public status status {
            get {
                return this.statusField1;
            }
            set {
                this.statusField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField2;
            }
            set {
                this.nameField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title {
            get {
                return this.titleField2;
            }
            set {
                this.titleField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public attachment[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public step[] steps {
            get {
                return this.stepsField1;
            }
            set {
                this.stepsField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:model.allure.qatools.yandex.ru")]
    public partial class attachment {
        
        private string titleField3;
        
        private string sourceField;
        
        private attachmenttype typeField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string title {
            get {
                return this.titleField3;
            }
            set {
                this.titleField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public attachmenttype type {
            get {
                return this.typeField1;
            }
            set {
                this.typeField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("attachment-type", Namespace="urn:model.allure.qatools.yandex.ru")]
    public enum attachmenttype {
        
        /// <remarks/>
        txt,
        
        /// <remarks/>
        html,
        
        /// <remarks/>
        xml,
        
        /// <remarks/>
        png,
        
        /// <remarks/>
        jpg,
        
        /// <remarks/>
        json,
        
        /// <remarks/>
        other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:model.allure.qatools.yandex.ru")]
    public partial class label {
        
        private string nameField3;
        
        private string valueField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string name {
            get {
                return this.nameField3;
            }
            set {
                this.nameField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string value {
            get {
                return this.valueField1;
            }
            set {
                this.valueField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:model.allure.qatools.yandex.ru")]
    public partial class parameter {
        
        private string nameField4;
        
        private string valueField2;
        
        private parameterkind kindField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string name {
            get {
                return this.nameField4;
            }
            set {
                this.nameField4 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string value {
            get {
                return this.valueField2;
            }
            set {
                this.valueField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public parameterkind kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("parameter-kind", Namespace="urn:model.allure.qatools.yandex.ru")]
    public enum parameterkind {
        
        /// <remarks/>
        argument,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("system-property")]
        systemproperty,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("environment-variable")]
        environmentvariable,
    }
}
