// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace allurecsharpcommons {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("test-suite-result", Namespace="urn:model.allure.qatools.yandex.ru")]
    [System.Xml.Serialization.XmlRootAttribute("test-suite", Namespace="urn:model.allure.qatools.yandex.ru", IsNullable=false)]
    public partial class TestSuiteResult {
        
		private long _startField;
        
		private long _stopField;
        
		private string _nameField;
        
		private string _titleField;
        
		private Description _descriptionField;
        
        private TestCaseResult[] _testcasesField;
        
		private Label[] _labelsField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public long Start {
            get {
                return this._startField;
            }
            set {
                this._startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public long Stop {
            get {
                return this._stopField;
            }
            set {
                this._stopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this._nameField;
            }
            set {
                this._nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Title {
            get {
                return this._titleField;
            }
            set {
                this._titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Description Description {
            get {
                return this._descriptionField;
            }
            set {
                this._descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(ElementName="test-cases", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="test-case", IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestCaseResult[] TestCases {
            get {
				return this._testcasesField;
            }
            set {
                this._testcasesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Label[] Labels {
            get {
                return this._labelsField1;
            }
            set {
                this._labelsField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:model.allure.qatools.yandex.ru")]
    public partial class Description {
        
		private DescriptionType _typeField;
        
		private string _valueField;
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue(DescriptionType.Text)]
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public DescriptionType Type {
            get {
                return this._typeField;
            }
            set {
                this._typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this._valueField;
            }
            set {
                this._valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("description-type", Namespace="urn:model.allure.qatools.yandex.ru")]
    public enum DescriptionType {
        
        /// <remarks/>
        Markdown,
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        Html,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute("test-case-result", Namespace="urn:model.allure.qatools.yandex.ru")]
    public partial class TestCaseResult {
        
		private long _startField1;
        
		private long _stopField1;
        
		private Status _statusField;
        
		private SeverityLevel _severityField;
        
		private string _nameField1;
        
		private string _titleField1;
        
		private Description _descriptionField1;
        
        private Failure failureField;
        
		private Step[] _stepsField;
        
		private Attachment[] _attachmentsField1;
        
		private Label[] _labelsField;
        
		private Parameter[] _parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public long Start {
            get {
                return this._startField1;
            }
            set {
                this._startField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public long Stop {
            get {
                return this._stopField1;
            }
            set {
                this._stopField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public Status Status {
            get {
                return this._statusField;
            }
            set {
                this._statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public SeverityLevel Severity {
            get {
                return this._severityField;
            }
            set {
                this._severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this._nameField1;
            }
            set {
                this._nameField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Title {
            get {
                return this._titleField1;
            }
            set {
                this._titleField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Description Description {
            get {
                return this._descriptionField1;
            }
            set {
                this._descriptionField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Failure Failure {
            get {
                return this.failureField;
            }
            set {
                this.failureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Step[] Steps {
            get {
                return this._stepsField;
            }
            set {
                this._stepsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Attachment[] Attachments {
            get {
                return this._attachmentsField1;
            }
            set {
                this._attachmentsField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Label[] Labels {
            get {
                return this._labelsField;
            }
            set {
                this._labelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Parameter[] Parameters {
            get {
                return this._parametersField;
            }
            set {
                this._parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:model.allure.qatools.yandex.ru")]
    public enum Status {
        
        /// <remarks/>
        Failed,
        
        /// <remarks/>
        Broken,
        
        /// <remarks/>
        Passed,
        
        /// <remarks/>
        Skipped,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("severity-level", Namespace="urn:model.allure.qatools.yandex.ru")]
    public enum SeverityLevel {
        
        /// <remarks/>
        Blocker,
        
        /// <remarks/>
        Critical,
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Minor,
        
        /// <remarks/>
        Trivial,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:model.allure.qatools.yandex.ru")]
    public partial class Failure {
        
		private string _messageField;
        
		private string _stacktraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message {
            get {
                return this._messageField;
            }
            set {
                this._messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stack-trace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Stacktrace {
            get {
                return this._stacktraceField;
            }
            set {
                this._stacktraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:model.allure.qatools.yandex.ru")]
    public partial class Step {
        
		private long _startField2;
        
		private long _stopField2;
        
		private Status _statusField1;
        
		private string _nameField2;
        
		private string _titleField2;
        
		private Attachment[] _attachmentsField;
        
		private Step[] _stepsField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public long Start {
            get {
                return this._startField2;
            }
            set {
                this._startField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public long Stop {
            get {
                return this._stopField2;
            }
            set {
                this._stopField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public Status Status {
            get {
                return this._statusField1;
            }
            set {
                this._statusField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this._nameField2;
            }
            set {
                this._nameField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Title {
            get {
                return this._titleField2;
            }
            set {
                this._titleField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Attachment[] Attachments {
            get {
                return this._attachmentsField;
            }
            set {
                this._attachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Step[] Steps {
            get {
                return this._stepsField1;
            }
            set {
                this._stepsField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:model.allure.qatools.yandex.ru")]
    public partial class Attachment {
        
		private string _titleField3;
        
		private string _sourceField;
        
		private AttachmentType _typeField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string Title {
            get {
                return this._titleField3;
            }
            set {
                this._titleField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string Source {
            get {
                return this._sourceField;
            }
            set {
                this._sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public AttachmentType Type {
            get {
                return this._typeField1;
            }
            set {
                this._typeField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("attachment-type", Namespace="urn:model.allure.qatools.yandex.ru")]
    public enum AttachmentType {
        
        /// <remarks/>
        Txt,
        
        /// <remarks/>
        Html,
        
        /// <remarks/>
        Xml,
        
        /// <remarks/>
        Png,
        
        /// <remarks/>
        Jpg,
        
        /// <remarks/>
        Json,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:model.allure.qatools.yandex.ru")]
    public partial class Label {
        
		private string _nameField3;
        
		private string _valueField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string Name {
            get {
                return this._nameField3;
            }
            set {
                this._nameField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string Value {
            get {
                return this._valueField1;
            }
            set {
                this._valueField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:model.allure.qatools.yandex.ru")]
    public partial class Parameter {
        
		private string _nameField4;
        
		private string _valueField2;
        
		private ParameterKind _kindField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string Name {
            get {
                return this._nameField4;
            }
            set {
                this._nameField4 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string Value {
            get {
                return this._valueField2;
            }
            set {
                this._valueField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public ParameterKind Kind {
            get {
                return this._kindField;
            }
            set {
                this._kindField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("parameter-kind", Namespace="urn:model.allure.qatools.yandex.ru")]
    public enum ParameterKind {
        
        /// <remarks/>
        Argument,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("system-property")]
        SystemProperty,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("environment-variable")]
        EnvironmentVariable,
    }
}
